apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  namespace: carlos
  name: caffeinetv-pionproject-dev-us-west-2-sg
spec:
  forProvider:
    region: us-west-2
    description: pionproject-internet-access
    tags:
      - key: Name
        value: pion-project-tag
    groupName: pionproject-carlos-group-name
    vpcId: vpc-00ff720b4358b24be
    ingress:
      - ipProtocol: udp
        fromPort: 10837
        toPort: 10846
        ipRanges:
          - cidrIp: 0.0.0.0/0
            description: internet access
      - ipProtocol: tcp
        fromPort: 2154
        toPort: 2158
        ipRanges:
          - cidrIp: 0.0.0.0/0
            description: internet access
      - ipProtocol: udp
        fromPort: 0
        toPort: 65535
        ipRanges:
          - cidrIp: 10.0.0.0/16
            description: access from all cluster
      - ipProtocol: tcp
        fromPort: 0
        toPort: 65535
        ipRanges:
          - cidrIp: 10.0.0.0/16
            description: access from all cluster
  providerConfigRef:
    name: provider-aws
