---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: udpsrv
  namespace: carlos
  labels:
    app: udpsrv
    app.kubernetes.io/name: udpsrv
    app.kubernetes.io/instance: udpsrv-carlos
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: udpsrv
      app.kubernetes.io/instance: udpsrv-carlos
  replicas: 1
  seviceName: udpsrv
  template:
    metadata:
      labels:
        app: udpsrv
        app.kubernetes.io/name: udpsrv
        app.kubernetes.io/instance: udpsrv-carlos
      annotations:
#        ad.datadoghq.com/istio-proxy.logs: '[{"source": "udprecv", "service": "udprecv"}]'
#        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: privileged
      hostNetwork: true
#      securityContext:
#        sysctls:
#        - name: net.ipv4.ip_local_port_range
#          value: "10837 10846"
      containers:
        - name: udpsrv
          env:
            - name: INGEST_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: INGEST_UDP_PORT_START
              value: "10837"
            - name: INGEST_UDP_PORT_END
              value: "10846"
           # - name: HEALTHCHECK_PORT
           #   value: "10000"
           # - name: PORTS
           #   value: "10837-10846"
          #image: quay.io/greg_caffeine/udprecv:0.1
          #image: quay.io/carlos_taffernaberry/server:1
          #image: quay.io/greg_caffeine/udprecv:0.3
          image: quay.io/caffeine/ingest_server:testing-1
          ports:
            - name: shepard
              containerPort: 2154
              protocol: TCP
            - name: kasumi
              containerPort: 2158
              protocol: TCP
            - name: pion1
              containerPort: 10837
              protocol: UDP
            - name: pion2
              containerPort: 10838
              protocol: UDP
            - name: pion3
              containerPort: 10839
              protocol: UDP
            - name: pion4
              containerPort: 10840
              protocol: UDP
            - name: pion5
              containerPort: 10841
              protocol: UDP
            - name: pion6
              containerPort: 10842
              protocol: UDP
            - name: pion7
              containerPort: 10843
              protocol: UDP
            - name: pion8
              containerPort: 10844
              protocol: UDP
            - name: pion9
              containerPort: 10845
              protocol: UDP
            - name: pion10
              containerPort: 10846
              protocol: UDP
            - name: hcheck
              containerPort: 10000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 2154
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 2154
            initialDelaySeconds: 15
            periodSeconds: 10
      nodeSelector:
        machine.openshift.io/cluster-api-machine-role: car 
        #node.kubernetes.io/instance-type: t3.medium
#      tolerations:
#        - key: node-role.kubernetes.io/piggy
#          operator: Exists
#          effect: NoSchedule
